build:
  environment:
    php: 7.4.11
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  paths:
    - src/
    - utils/

tools:
  external_code_coverage:
    timeout: 300
